DROP DATABASE IF EXISTS db_triangle;
CREATE DATABASE db_triangle;
USE db_triangle;

DROP TABLE IF EXISTS triangle;
CREATE TABLE triangle (
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    x1 FLOAT SIGNED,
    x2 FLOAT SIGNED,
    x3 FLOAT SIGNED,
    y1 FLOAT SIGNED,
    y2 FLOAT SIGNED,
    y3 FLOAT SIGNED
);

